// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWZGYLKs_Bnt83KXB2aUyuvAzwc6YHS2k',
    appId: '1:758687413898:web:a87e94fb250db6bebe1f73',
    messagingSenderId: '758687413898',
    projectId: 'flutter-firebase-app-776b5',
    authDomain: 'flutter-firebase-app-776b5.firebaseapp.com',
    storageBucket: 'flutter-firebase-app-776b5.firebasestorage.app',
    measurementId: 'G-11H9563DGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD9CLTwJ6uF858Q2mSqyZkCfrH-mTCItU',
    appId: '1:758687413898:android:ad18bbf68a7f8c58be1f73',
    messagingSenderId: '758687413898',
    projectId: 'flutter-firebase-app-776b5',
    storageBucket: 'flutter-firebase-app-776b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGl7fis7IgmNf8QB4yCMZew4WS1l7yul4',
    appId: '1:758687413898:ios:3ccb8da4013e1f9ebe1f73',
    messagingSenderId: '758687413898',
    projectId: 'flutter-firebase-app-776b5',
    storageBucket: 'flutter-firebase-app-776b5.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseTugas8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGl7fis7IgmNf8QB4yCMZew4WS1l7yul4',
    appId: '1:758687413898:ios:3ccb8da4013e1f9ebe1f73',
    messagingSenderId: '758687413898',
    projectId: 'flutter-firebase-app-776b5',
    storageBucket: 'flutter-firebase-app-776b5.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseTugas8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWZGYLKs_Bnt83KXB2aUyuvAzwc6YHS2k',
    appId: '1:758687413898:web:348c6e3651a43f9bbe1f73',
    messagingSenderId: '758687413898',
    projectId: 'flutter-firebase-app-776b5',
    authDomain: 'flutter-firebase-app-776b5.firebaseapp.com',
    storageBucket: 'flutter-firebase-app-776b5.firebasestorage.app',
    measurementId: 'G-F94FJE49JW',
  );
}
